# Generated by Django 3.2 on 2021-10-10 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0002_auto_20211010_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 1, 10, 13, 918823)),
        ),
        migrations.AlterField(
            model_name='order',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 1, 10, 13, 918871)),
        ),
        migrations.AlterField(
            model_name='order',
            name='resume',
            field=models.TextField(null=True),
        ),
    ]
