# Generated by Django 3.2 on 2021-10-10 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0003_auto_20211010_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 8, 30, 134472)),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 22, 8, 30, 134911)),
        ),
        migrations.AlterField(
            model_name='order',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 22, 8, 30, 134930)),
        ),
    ]
