# Generated by Django 3.2 on 2021-10-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0009_alter_account_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='user.png', null=True, upload_to='profile_pic'),
        ),
    ]
