# Generated by Django 3.2.7 on 2021-10-14 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0011_remove_account_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='rate',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=255)),
                ('comment', models.TextField(null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_review.reviewer')),
            ],
        ),
    ]
