# Generated by Django 3.2.7 on 2021-10-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0012_auto_20211014_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='uaddsser.png', null=True, upload_to='profile_pic'),
        ),
    ]
