# Generated by Django 3.2.8 on 2021-10-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0015_alter_order_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes'),
        ),
    ]
