# Generated by Django 3.2.8 on 2021-10-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0016_alter_order_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finished_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='delivery_time',
            field=models.CharField(choices=[('delivery_1', 'One week'), ('delivery_2', 'Two weeks'), ('delivery_3', 'Three weeks'), ('delivery_4', 'Four weeks or more')], max_length=255),
        ),
    ]
