# Generated by Django 3.2.8 on 2021-11-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0002_auto_20211121_0055'),
        ('resume_review', '0016_alter_order_resume'),
    ]

    operations = [
    ]
