# Generated by Django 3.2.8 on 2021-11-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0018_alter_reviewer_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
