# Generated by Django 3.2.8 on 2021-11-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0020_comment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
