# Generated by Django 3.2.8 on 2021-11-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_review', '0020_auto_20211121_2146'),
        ('resume_review', '0021_alter_reviewer_rate'),
    ]

    operations = [
    ]
